### ISSUE TITLE
Add an external CSS to the sample HTML project

### ISSUE THREAD

**Issue by rmahil7** [pralinkhaira/Project-Wizard#17]
Create a CSS file with your styles, like "styles.css".
Link the CSS file in the HTML <head> section using <link> tags.
Upload both HTML and CSS files. (Projects/Sample Project/html_css)
In a GitHub issue comment, explain that you added an external CSS file for custom styling.
[Sample Project](https://github.com/pralinkhaira/Project-Wizard/tree/main/Projects/Sample%20Project/html_css)

**Comment by pralinkhaira** [comment]
Good Job!!
