### ISSUE TITLE
Cryptographer

### ISSUE THREAD

**Issue by spyke7** [pralinkhaira/Project-Wizard#19]
Hey there
I want to contribute a python program that will encrypt and decrypt the contents of a text file
Please assign this to me

**Comment by zemichael1234** [comment]
what about encrypting and decrypting a exe file using stub dos. if you agree we can work on that in c++

**Comment by spyke7** [comment]
Yes that can be done
But I have to first learn about encrypting and decrypting and using hash in c++ and also changing the assembly in exe.
Do you have a repo where we can work?
