### ISSUE TITLE
[Problem] : Grid Unique Paths LeetCode Problem

### ISSUE THREAD

**Issue by AKACHI-4** [pralinkhaira/Project-Wizard#26]
## What ?
I'd like to contribute a cpp solution for the leetcode problem (grid unique paths)[https://leetcode.com/problems/unique-paths/].

## Code of Conduct

- [x] I agree to follow this project's Code of Conduct

<br>
<br>

> **Kindly assign it to me under _HacktoberFest'23_** 
> **I will surely complete it ASAP**

**Comment by pralinkhaira** [comment]
# Done Assigned
